definitions:
  schemas.CreateTodoInput:
    properties:
      title:
        type: string
    type: object
  schemas.Todo:
    properties:
      createdAt:
        type: string
      done:
        type: boolean
      doneAt:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /todos:
    get:
      description: Get a list of all todos
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Todo'
      tags:
      - todos
    post:
      description: Create a new todo
      parameters:
      - description: input
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/schemas.CreateTodoInput'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Todo'
      tags:
      - todos
swagger: "2.0"
